# ========================
# === Alacritty Config ===
# ========================

import = [
    "~/.cfg/alacritty/settings.toml",
    "~/.cfg/alacritty/font.toml",
    "~/.cfg/alacritty/colors.toml"
]
