# ====================
# === Cargo Config ===
# ====================

[alias]
i  = 'install'
ui = 'uninstall'

a = 'add'
n = 'new'

nb = 'new --bin'
nl = 'new --lib'

cl = 'clippy'
rr = 'run --release'
br = 'build --release'
