# =======================
# === Tmux Dev Preset ===
# =======================

name: dev
# set project root with root setting
root: <%= @settings['root'] ? File.expand_path(@settings['root'], Dir.pwd) : '~/' %>

windows:
  - shell:
      # ┃┣┃ layout
      layout: 6c2a,203x58,0,0{101x58,0,0,0,101x58,102,0[101x29,102,0,4,101x28,102,30,5]}
      panes:
        -
        -
        -

  - editor: <%= ENV['EDITOR'] %>
