# =======================
# === Tmux Dev Preset ===
# =======================

# get project root from args
name: <%= @args[0] ? File.basename(@args[0]) : 'dev' %>
root: <%= @args[0] ? File.expand_path(@args[0], Dir.pwd) : '~/' %>

windows:
  - shell:
      layout: 6c2a,203x58,0,0{101x58,0,0,0,101x58,102,0[101x29,102,0,4,101x28,102,30,5]}
      panes:
        -
        -
        -

  - editor: anyvim
