# ======================
# === RuboCop Config ===
# ======================

AllCops:
  # enable new cops
  NewCops: enable

# allow no empty line after guard clause
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# disable hash alignment
Layout/HashAlignment:
  Enabled: false
  EnforcedColonStyle: table

# disable broken indentation
Layout/FirstArgumentIndentation:
  Enabled: false

# set max method length
Metrics/MethodLength:
  Max: 50

# set max class length
Metrics/ClassLength:
  Max: 250

# set max module length
Metrics/ModuleLength:
  Max: 250

# disable cyclomatic complexity
Metrics/CyclomaticComplexity:
  Enabled: false

# disable abc size
Metrics/AbcSize:
  Enabled: false

# disable perceived complexity
Metrics/PerceivedComplexity:
  Enabled: false

# allow single line methods
Style/SingleLineMethods:
  Enabled: false

# allow no frozen string literal comment
Style/FrozenStringLiteralComment:
  Enabled: false

# set preferred name for errors
Naming/RescuedExceptionsVariableName:
  PreferredName: error
