# ======================
# === RuboCop Config ===
# ======================

AllCops:
  # enable new cops
  NewCops: enable

  # ruby version
  TargetRubyVersion: 3.1

# allow no empty line after guard clause
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# disable hash alignment
Layout/HashAlignment:
  Enabled: false

# disable broken indentation
Layout/FirstArgumentIndentation:
  Enabled: false

# max block length
Metrics/BlockLength:
  Max: 50

# max method length
Metrics/MethodLength:
  Max: 50

# max class length
Metrics/ClassLength:
  Max: 250

# max module length
Metrics/ModuleLength:
  Max: 250

# disable cyclomatic complexity
Metrics/CyclomaticComplexity:
  Enabled: false

# disable perceived complexity
Metrics/PerceivedComplexity:
  Enabled: false

# disable abc size
Metrics/AbcSize:
  Enabled: false

# allow single line methods
Style/SingleLineMethods:
  Enabled: false

# allow no frozen string literal comment
Style/FrozenStringLiteralComment:
  Enabled: false

# preferred name for errors
Naming/RescuedExceptionsVariableName:
  PreferredName: error

# fix rubocop crashing
Lint/EmptyConditionalBody:
  Enabled: false
