#!/usr/bin/env bash

# ====================
# === Yabai Config ===
# ====================

# default to bsp
yabai -m config layout bsp

# window padding
yabai -m config     \
  top_padding    25 \
  bottom_padding 25 \
  left_padding   25 \
  right_padding  25 \
  window_gap     10

# move mouse to focus
yabai -m config mouse_follows_focus on
