#!/usr/bin/env bash

# ====================
# === Yabai Config ===
# ====================

# load system scripts
yabai --load-sa

# default to bsp
yabai -m config layout bsp

# move mouse to focus
yabai -m config mouse_follows_focus on

# hide window shadow
yabai -m config window_shadow off

# window padding
yabai -m config     \
  top_padding    15 \
  bottom_padding 15 \
  left_padding   15 \
  right_padding  15 \
  window_gap     10

source ~/.cfg/colemak/yabai/colemak.zsh
