#!/usr/bin/env zsh

# ======================
# === Newsboat Pager ===
# ======================

# read file
cat $1 |

# convert html to markdown
turndown |

# remove lines from newsboat
tail -n +3 |

# remove blank code blocks
sed -E 's/^(> )+$//' |

# format markdown for viewing
glow -s ~/.cfg/glow/style.json - |

# page output
less -rc
