# ==================
# === LSD Config ===
# ==================

# show hidden
display: almost-all

# show indicators
indicators: true

# date format
date: '+%d %b %y %I:%M %p'

# displayed blocks
blocks:
  - permission
  - size
  - date
  - name
